### ISSUE TITLE
How to limit characters and words ?

### ISSUE THREAD

**Issue by iit2011081** [Textalk/angular-schema-form-tinymce#4]
I want to specify min and max characters or words, where do I need to specify that ? I didn't find any option to do so.

**Comment by Dervisevic** [comment]
That's not supported, i looked at tinyMCE and it doesn't seem to support that either. You could put a limit in the schema i suppose and make it invalid if it's over that, but that would be characters and whitespace and all.

**Comment by iit2011081** [comment]
Ok..not an issue I will do it on my end. Is it possible to send custom validation message ? e.g.
```
form = [
  {
    "key": "name",
    "validationMessages": {
      "maxCharsReached": "The username is already taken"
    }
  }
]
$scope.$broadcast('schemaForm.error.name','maxCharsReached',true);
```

**Comment by Dervisevic** [comment]
Yeah that should be possible, more information here: https://github.com/json-schema-form/angular-schema-form/blob/master/docs/index.md#custom-validation

**Comment by iit2011081** [comment]
I tried but every time it says same message "Field does not validate" . I tried following things -
```
form = [
  {
    "key": "name",
    "validationMessages": {
      "maxCharsReached": "The username is already taken"
    }
  }
]
$scope.$broadcast('schemaForm.error.name','maxCharsReached',false);
$scope.$broadcast('schemaForm.error.name','maxCharsReached','max chars reached'); 
```
